name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Tidy
        run: go mod tidy
      - name: Build
        run: go build ./...
      - name: Test (offline)
        env:
          AIGIT_DISABLE_AUTOSTART: '1'
        run: go test -offline ./...

  test-online:
    if: ${{ secrets.OPENROUTER_API_KEY != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Tidy
        run: go mod tidy
      - name: Build
        run: go build ./...
      - name: Test (online)
        env:
          AIGIT_DISABLE_AUTOSTART: '1'
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: go test ./...
