name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Set up GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          # Use a Personal Access Token with repo scope that can access both
          # this repo and the Homebrew tap repo. Create a secret named
          # BREW_GITHUB_TOKEN in the repository settings.
          GITHUB_TOKEN: ${{ secrets.BREW_GITHUB_TOKEN }}
